/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Codigos.java
 *
 * Created on Jun 2, 2013, 4:25:39 AM
 */
package br.bcn.admclin.interfacesGraficas.menu.atendimentos.fichasDeAtendimentos;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author Theodoro
 */
public class HistoriaClinica extends javax.swing.JFrame {

    public static String alpha  = ""; 
    public static String number = ""; 
    public static String nomePaciente = "";
    public static String textoHistoria = "";
    public static String dirName = "";

    public HistoriaClinica() {
        setIconImage(getToolkit().createImage(getClass().getResource("/br/bcn/admclin/imagens/imagemIconePrograma.png")));
        Toolkit tk = Toolkit.getDefaultToolkit();
        java.awt.Dimension screenSize = tk.getScreenSize();
        this.setLocation(screenSize.width / 2 - 512, 0);
        this.setAlwaysOnTop(true);
        initComponents();
        Atualizar.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Atualizar = new javax.swing.JButton();
        Atualizar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
            }
        });
        jScrollPane1 = new javax.swing.JScrollPane();
        historiaText = new javax.swing.JTextArea();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        Atualizar.setIcon(new ImageIcon(HistoriaClinica.class.getResource("/br/bcn/admclin/imagens/atualizar.png"))); // NOI18N
        Atualizar.setText("Atualizar");
        Atualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AtualizarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AtualizarMouseReleased(evt);
            }
        });

        historiaText.setColumns(20);
        historiaText.setRows(5);
        historiaText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                historiaTextKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(historiaText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(Atualizar)
                    .addGap(67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(Alignment.LEADING)
                        .addComponent(Atualizar, GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtualizarMousePressed

    }//GEN-LAST:event_AtualizarMousePressed
    
    public void createHistoriaText() {
            if (historiaText.getText().length() > 0) {
            
            //----------------------------------------------------------------------------------Create History
            String histoText    = historiaText.getText();
            int totalLinesh     = historiaText.getLineCount();
            textoHistoria = "";
            for (int i=0; i < totalLinesh; i++) {
                    try {
                        int start    = historiaText.getLineStartOffset(i);
                        int end      = historiaText.getLineEndOffset(i);
                        String line  = histoText.substring(start, end);
                        String sline = line.replaceAll("\\n","\\[\\]");                
                        textoHistoria += sline;
                    } catch (Exception ex) { }
            }
            //System.out.println("CompleteHisto: "+Historia);
            //-----------------------------------------------------------------------------------History Created
            
        }
}
    private void AtualizarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtualizarMouseReleased
            //createHistoriaText();
            //System.out.println("Texto "+textoHistoria);
            //String retorno = PaginaAsp.saveHistoriaN2(dirName,textoHistoria,jFLogin.userName);
            //if (retorno.indexOf("OK") > -1) {
            //    JOptionPane.showMessageDialog(null, "Historia Gravada com sucesso...");
            //}
    }//GEN-LAST:event_AtualizarMouseReleased

    private void historiaTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_historiaTextKeyTyped
        Atualizar.setEnabled(true);
    }//GEN-LAST:event_historiaTextKeyTyped

    public static void sleepTime(int miliseconds){
        try{
            Thread.currentThread().sleep(miliseconds);
        }
        catch(Exception e){
            //
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoriaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoriaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoriaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoriaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new HistoriaClinica().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    public static javax.swing.JTextArea historiaText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
