package br.bcn.admclin.interfacesGraficas.menu.cadastros.agenda;

import java.awt.Dimension;
import java.awt.Insets;

import javax.swing.border.EmptyBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableModel;

import br.bcn.admclin.ClasseAuxiliares.MetodosUteis;
import br.bcn.admclin.interfacesGraficas.janelaPrincipal.janelaPrincipal;

import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextField;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author cesar
 */
public class JIFCadastroAgendaTurnos extends javax.swing.JInternalFrame {

    private static final long serialVersionUID = 1L;
    /**
     * Creates new form JIFCadastroAgenda
     */
    public JIFCadastroAgendaTurnos() {
        initComponents();
        tirandoBarraDeTitulo();
        jTableSegunda.setVisible(false);
        jTableTerca.setVisible(false);
        jTableQuarta.setVisible(false);
        jTableQuinta.setVisible(false);
        jTableSexta.setVisible(false);
        jTableSabado.setVisible(false);
        jTableDomingo.setVisible(false);
        jBReplicar.setEnabled(false);
        
        jTFDuracaoSegunda.setEnabled(false);
        jTFDuracaoTerca.setEnabled(false);
        jTFDuracaoQuarta.setEnabled(false);
        jTFDuracaoQuinta.setEnabled(false);
        jTFDuracaoSexta.setEnabled(false);
        jTFDuracaoSabado.setEnabled(false);
        jTFDuracaoDomingo.setEnabled(false);
        
    }
    
    public void tirandoBarraDeTitulo() {
        ((BasicInternalFrameUI) this.getUI()).getNorthPane().setPreferredSize(new Dimension(0, 0));
        this.setBorder(new EmptyBorder(new Insets(0, 0, 0, 0)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSegunda = new javax.swing.JTable();
        jCBAtivaSegunda = new javax.swing.JCheckBox();
        jBReplicar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTerca = new javax.swing.JTable();
        jCBAtivaTerca = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableQuarta = new javax.swing.JTable();
        jCBAtivaQuarta = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableQuinta = new javax.swing.JTable();
        jCBAtivaQuinta = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableSabado = new javax.swing.JTable();
        jCBAtivaSabado = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableDomingo = new javax.swing.JTable();
        jCBAtivaDomingo = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableSexta = new javax.swing.JTable();
        jCBAtivaSexta = new javax.swing.JCheckBox();
        jBVoltar = new javax.swing.JButton();
        jBVoltar.setIcon(new ImageIcon(JIFCadastroAgendaTurnos.class.getResource("/br/bcn/admclin/imagens/imagemSetaParaEsquerda.png")));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Segunda-Feira", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTableSegunda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Início", "00:00", "00:00", "00:00", "00:00"},
                {"Fim", "00:00", "00:00", "00:00", "00:00"}
            },
            new String [] {
                "", "Manhã", "Tarde", "Noite", "Madrugada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableSegunda);

        jCBAtivaSegunda.setText("Ativa");
        jCBAtivaSegunda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAtivaSegundaActionPerformed(evt);
            }
        });

        jBReplicar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jBReplicar.setText("Replicar");
        jBReplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReplicarActionPerformed(evt);
            }
        });
        
        JLabel lblDurao = new JLabel("Duração");
        
        jTFDuracaoSegunda = new JFormattedTextField(MetodosUteis.mascaraParaJFormattedTextField("##:##"));
        jTFDuracaoSegunda.setText("00:00");
        jTFDuracaoSegunda.setColumns(10);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jCBAtivaSegunda)
                    .addGap(18)
                    .addComponent(lblDurao)
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(jTFDuracaoSegunda, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                    .addComponent(jBReplicar))
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 374, GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(jBReplicar, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCBAtivaSegunda)
                        .addComponent(lblDurao)
                        .addComponent(jTFDuracaoSegunda, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
        );
        jPanel1.setLayout(jPanel1Layout);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Terça-Feira", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTableTerca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Início", "00:00", "00:00", "00:00", "00:00"},
                {"Fim", "00:00", "00:00", "00:00", "00:00"}
            },
            new String [] {
                "", "Manhã", "Tarde", "Noite", "Madrugada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableTerca);

        jCBAtivaTerca.setText("Ativa");
        jCBAtivaTerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAtivaTercaActionPerformed(evt);
            }
        });
        
        label_1 = new JLabel("Duração");
        
        jTFDuracaoTerca = new JFormattedTextField(MetodosUteis.mascaraParaJFormattedTextField("##:##"));
        jTFDuracaoTerca.setText("00:00");
        jTFDuracaoTerca.setColumns(10);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(Alignment.TRAILING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jCBAtivaTerca)
                    .addGap(18)
                    .addComponent(label_1, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(jTFDuracaoTerca, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                    .addGap(209))
                .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 374, GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(6)
                            .addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
                                .addComponent(label_1)
                                .addComponent(jCBAtivaTerca)))
                        .addComponent(jTFDuracaoTerca, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
        );
        jPanel2.setLayout(jPanel2Layout);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quarta-Feira", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTableQuarta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Início", "00:00", "00:00", "00:00", "00:00"},
                {"Fim", "00:00", "00:00", "00:00", "00:00"}
            },
            new String [] {
                "", "Manhã", "Tarde", "Noite", "Madrugada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableQuarta);

        jCBAtivaQuarta.setText("Ativa");
        jCBAtivaQuarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAtivaQuartaActionPerformed(evt);
            }
        });
        
        jTFDuracaoQuarta = new JFormattedTextField(MetodosUteis.mascaraParaJFormattedTextField("##:##"));
        jTFDuracaoQuarta.setText("00:00");
        jTFDuracaoQuarta.setColumns(10);
        
        label_3 = new JLabel("Duração");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(Alignment.TRAILING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jCBAtivaQuarta)
                    .addGap(18)
                    .addComponent(label_3, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(jTFDuracaoQuarta, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addGap(208))
                .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 374, GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(7)
                            .addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
                                .addComponent(label_3)
                                .addComponent(jCBAtivaQuarta)))
                        .addComponent(jTFDuracaoQuarta, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(jScrollPane3, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
        );
        jPanel3.setLayout(jPanel3Layout);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quinta-Feira", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTableQuinta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Início", "00:00", "00:00", "00:00", "00:00"},
                {"Fim", "00:00", "00:00", "00:00", "00:00"}
            },
            new String [] {
                "", "Manhã", "Tarde", "Noite", "Madrugada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableQuinta);

        jCBAtivaQuinta.setText("Ativa");
        jCBAtivaQuinta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAtivaQuintaActionPerformed(evt);
            }
        });
        
        jTFDuracaoQuinta = new JFormattedTextField(MetodosUteis.mascaraParaJFormattedTextField("##:##"));
        jTFDuracaoQuinta.setText("00:00");
        jTFDuracaoQuinta.setColumns(10);
        
        label = new JLabel("Duração");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jCBAtivaQuinta)
                    .addGap(18)
                    .addComponent(label, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(jTFDuracaoQuinta, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, 374, GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(6)
                            .addComponent(jCBAtivaQuinta))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(6)
                            .addComponent(label))
                        .addComponent(jTFDuracaoQuinta, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(jScrollPane4, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
        );
        jPanel4.setLayout(jPanel4Layout);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sabado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTableSabado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Início", "00:00", "00:00", "00:00", "00:00"},
                {"Fim", "00:00", "00:00", "00:00", "00:00"}
            },
            new String [] {
                "", "Manhã", "Tarde", "Noite", "Madrugada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableSabado);

        jCBAtivaSabado.setText("Ativa");
        jCBAtivaSabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAtivaSabadoActionPerformed(evt);
            }
        });
        
        jTFDuracaoSabado = new JFormattedTextField(MetodosUteis.mascaraParaJFormattedTextField("##:##"));
        jTFDuracaoSabado.setText("00:00");
        jTFDuracaoSabado.setColumns(10);
        
        label_4 = new JLabel("Duração");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(Alignment.TRAILING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(jCBAtivaSabado)
                    .addGap(18)
                    .addComponent(label_4, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(jTFDuracaoSabado, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                    .addGap(209))
                .addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, 374, GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(8)
                            .addGroup(jPanel5Layout.createParallelGroup(Alignment.BASELINE)
                                .addComponent(label_4)
                                .addComponent(jCBAtivaSabado)))
                        .addComponent(jTFDuracaoSabado, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
        );
        jPanel5.setLayout(jPanel5Layout);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domingo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTableDomingo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Início", "00:00", "00:00", "00:00", "00:00"},
                {"Fim", "00:00", "00:00", "00:00", "00:00"}
            },
            new String [] {
                "", "Manhã", "Tarde", "Noite", "Madrugada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTableDomingo);

        jCBAtivaDomingo.setText("Ativa");
        jCBAtivaDomingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAtivaDomingoActionPerformed(evt);
            }
        });
        
        jTFDuracaoDomingo = new JFormattedTextField(MetodosUteis.mascaraParaJFormattedTextField("##:##"));
        jTFDuracaoDomingo.setText("00:00");
        jTFDuracaoDomingo.setColumns(10);
        
        label_5 = new JLabel("Duração");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(Alignment.TRAILING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(jCBAtivaDomingo)
                    .addPreferredGap(ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                    .addComponent(label_5, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(jTFDuracaoDomingo, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                    .addGap(209))
                .addComponent(jScrollPane6, GroupLayout.PREFERRED_SIZE, 374, GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(9)
                            .addGroup(jPanel6Layout.createParallelGroup(Alignment.BASELINE)
                                .addComponent(label_5)
                                .addComponent(jCBAtivaDomingo)))
                        .addComponent(jTFDuracaoDomingo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(jScrollPane6, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
        );
        jPanel6.setLayout(jPanel6Layout);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexta-Feira", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTableSexta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Início", "00:00", "00:00", "00:00", "00:00"},
                {"Fim", "00:00", "00:00", "00:00", "00:00"}
            },
            new String [] {
                "", "Manhã", "Tarde", "Noite", "Madrugada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTableSexta);

        jCBAtivaSexta.setText("Ativa");
        jCBAtivaSexta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAtivaSextaActionPerformed(evt);
            }
        });
        
        label_2 = new JLabel("Duração");
        
        jTFDuracaoSexta = new JFormattedTextField(MetodosUteis.mascaraParaJFormattedTextField("##:##"));
        jTFDuracaoSexta.setText("00:00");
        jTFDuracaoSexta.setColumns(10);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(Alignment.TRAILING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addComponent(jCBAtivaSexta)
                    .addPreferredGap(ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                    .addComponent(label_2, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(jTFDuracaoSexta, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
                    .addGap(208))
                .addComponent(jScrollPane7, GroupLayout.PREFERRED_SIZE, 374, GroupLayout.PREFERRED_SIZE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGroup(jPanel7Layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGap(7)
                            .addGroup(jPanel7Layout.createParallelGroup(Alignment.BASELINE)
                                .addComponent(label_2)
                                .addComponent(jCBAtivaSexta)))
                        .addComponent(jTFDuracaoSexta, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addComponent(jScrollPane7, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
        );
        jPanel7.setLayout(jPanel7Layout);

        jBVoltar.setText("Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBReplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReplicarActionPerformed
        //ativa os check box
        jCBAtivaTerca.setSelected(true);
        jCBAtivaQuarta.setSelected(true);
        jCBAtivaQuinta.setSelected(true);
        jCBAtivaSexta.setSelected(true);
        jCBAtivaSabado.setSelected(true);
        jCBAtivaDomingo.setSelected(true);
        
        //ativa as durações
        jTFDuracaoTerca.setEnabled(true);
        jTFDuracaoQuarta.setEnabled(true);
        jTFDuracaoQuinta.setEnabled(true);
        jTFDuracaoSexta.setEnabled(true);
        jTFDuracaoSabado.setEnabled(true);
        jTFDuracaoDomingo.setEnabled(true);
        
        //prenche as durações
        jTFDuracaoTerca.setText(jTFDuracaoSegunda.getText());
        jTFDuracaoQuarta.setText(jTFDuracaoSegunda.getText());
        jTFDuracaoQuinta.setText(jTFDuracaoSegunda.getText());
        jTFDuracaoSexta.setText(jTFDuracaoSegunda.getText());
        jTFDuracaoSabado.setText(jTFDuracaoSegunda.getText());
        jTFDuracaoDomingo.setText(jTFDuracaoSegunda.getText());
        
        //libera e preenche tabelas
        jTableTerca.setVisible(true);
        jTableQuarta.setVisible(true);
        jTableQuinta.setVisible(true);
        jTableSexta.setVisible(true);
        jTableSabado.setVisible(true);
        jTableDomingo.setVisible(true);
        
        //replicando os valores da tabela
        //nao pode ser pelo modelo, pq depois se muda a segunda, muda todo o resto
        String start1 = String.valueOf(jTableSegunda.getValueAt(0, 1));
        String end1 = String.valueOf(jTableSegunda.getValueAt(1, 1));
        String start2 = String.valueOf(jTableSegunda.getValueAt(0, 2));
        String end2 = String.valueOf(jTableSegunda.getValueAt(1, 2));
        String start3 = String.valueOf(jTableSegunda.getValueAt(0, 3));
        String end3 = String.valueOf(jTableSegunda.getValueAt(1, 3));
        String start4 = String.valueOf(jTableSegunda.getValueAt(0, 4));
        String end4 = String.valueOf(jTableSegunda.getValueAt(1, 4));
        
        jTableTerca.setValueAt(start1, 0, 1);
        jTableTerca.setValueAt(end1, 1, 1);
        jTableTerca.setValueAt(start2, 0, 2);
        jTableTerca.setValueAt(end2, 1, 2);
        jTableTerca.setValueAt(start3, 0, 3);
        jTableTerca.setValueAt(end3, 1, 3);
        jTableTerca.setValueAt(start4, 0, 4);
        jTableTerca.setValueAt(end4, 1, 4);
        
        jTableQuarta.setValueAt(start1, 0, 1);
        jTableQuarta.setValueAt(end1, 1, 1);
        jTableQuarta.setValueAt(start2, 0, 2);
        jTableQuarta.setValueAt(end2, 1, 2);
        jTableQuarta.setValueAt(start3, 0, 3);
        jTableQuarta.setValueAt(end3, 1, 3);
        jTableQuarta.setValueAt(start4, 0, 4);
        jTableQuarta.setValueAt(end4, 1, 4);
        
        jTableQuinta.setValueAt(start1, 0, 1);
        jTableQuinta.setValueAt(end1, 1, 1);
        jTableQuinta.setValueAt(start2, 0, 2);
        jTableQuinta.setValueAt(end2, 1, 2);
        jTableQuinta.setValueAt(start3, 0, 3);
        jTableQuinta.setValueAt(end3, 1, 3);
        jTableQuinta.setValueAt(start4, 0, 4);
        jTableQuinta.setValueAt(end4, 1, 4);
        
        jTableSexta.setValueAt(start1, 0, 1);
        jTableSexta.setValueAt(end1, 1, 1);
        jTableSexta.setValueAt(start2, 0, 2);
        jTableSexta.setValueAt(end2, 1, 2);
        jTableSexta.setValueAt(start3, 0, 3);
        jTableSexta.setValueAt(end3, 1, 3);
        jTableSexta.setValueAt(start4, 0, 4);
        jTableSexta.setValueAt(end4, 1, 4);
        
        jTableSabado.setValueAt(start1, 0, 1);
        jTableSabado.setValueAt(end1, 1, 1);
        jTableSabado.setValueAt(start2, 0, 2);
        jTableSabado.setValueAt(end2, 1, 2);
        jTableSabado.setValueAt(start3, 0, 3);
        jTableSabado.setValueAt(end3, 1, 3);
        jTableSabado.setValueAt(start4, 0, 4);
        jTableSabado.setValueAt(end4, 1, 4);
        
        jTableDomingo.setValueAt(start1, 0, 1);
        jTableDomingo.setValueAt(end1, 1, 1);
        jTableDomingo.setValueAt(start2, 0, 2);
        jTableDomingo.setValueAt(end2, 1, 2);
        jTableDomingo.setValueAt(start3, 0, 3);
        jTableDomingo.setValueAt(end3, 1, 3);
        jTableDomingo.setValueAt(start4, 0, 4);
        jTableTerca.setValueAt(end4, 1, 4);
    }//GEN-LAST:event_jBReplicarActionPerformed

    private void jCBAtivaSegundaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBAtivaSegundaActionPerformed
        if(jCBAtivaSegunda.isSelected()){
            jTableSegunda.setVisible(true);
            jTFDuracaoSegunda.setEnabled(true);
            jBReplicar.setEnabled(true);
        }else{
            jTableSegunda.setVisible(false); 
            jTFDuracaoSegunda.setEnabled(false);
            jBReplicar.setEnabled(false);
        }
    }//GEN-LAST:event_jCBAtivaSegundaActionPerformed

    private void jCBAtivaTercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBAtivaTercaActionPerformed
        if(jCBAtivaTerca.isSelected()){
            jTableTerca.setVisible(true);
            jTFDuracaoTerca.setEnabled(true);
        }else{
            jTableTerca.setVisible(false); 
            jTFDuracaoTerca.setEnabled(false);
        }
    }//GEN-LAST:event_jCBAtivaTercaActionPerformed

    private void jCBAtivaQuartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBAtivaQuartaActionPerformed
        if(jCBAtivaQuarta.isSelected()){
            jTableQuarta.setVisible(true);
            jTFDuracaoQuarta.setEnabled(true);
        }else{
            jTableQuarta.setVisible(false); 
            jTFDuracaoQuarta.setEnabled(false);
        }
    }//GEN-LAST:event_jCBAtivaQuartaActionPerformed

    private void jCBAtivaQuintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBAtivaQuintaActionPerformed
        if(jCBAtivaQuinta.isSelected()){
            jTableQuinta.setVisible(true);
            jTFDuracaoQuinta.setEnabled(true);
        }else{
            jTableQuinta.setVisible(false);  
            jTFDuracaoQuinta.setEnabled(false);
        }
    }//GEN-LAST:event_jCBAtivaQuintaActionPerformed

    private void jCBAtivaSextaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBAtivaSextaActionPerformed
        if(jCBAtivaSexta.isSelected()){
            jTableSexta.setVisible(true);
            jTFDuracaoSexta.setEnabled(true);
        }else{
            jTableSexta.setVisible(false);  
            jTFDuracaoSexta.setEnabled(false);
        }
    }//GEN-LAST:event_jCBAtivaSextaActionPerformed

    private void jCBAtivaSabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBAtivaSabadoActionPerformed
        if(jCBAtivaSabado.isSelected()){
            jTableSabado.setVisible(true);
            jTFDuracaoSabado.setEnabled(true);
        }else{
            jTableSabado.setVisible(false);  
            jTFDuracaoSabado.setEnabled(false);
        }
    }//GEN-LAST:event_jCBAtivaSabadoActionPerformed

    private void jCBAtivaDomingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBAtivaDomingoActionPerformed
        if(jCBAtivaDomingo.isSelected()){
            jTableDomingo.setVisible(true);
            jTFDuracaoDomingo.setEnabled(true);
        }else{
            jTableDomingo.setVisible(false);  
            jTFDuracaoDomingo.setEnabled(false);
        }
    }//GEN-LAST:event_jCBAtivaDomingoActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        this.setVisible(false);
        janelaPrincipal.internalFrameCadastroAgendasDesc.setVisible(true);
    }//GEN-LAST:event_jBVoltarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBReplicar;
    private javax.swing.JButton jBVoltar;
    public javax.swing.JCheckBox jCBAtivaDomingo;
    public javax.swing.JCheckBox jCBAtivaQuarta;
    public javax.swing.JCheckBox jCBAtivaQuinta;
    public javax.swing.JCheckBox jCBAtivaSabado;
    public javax.swing.JCheckBox jCBAtivaSegunda;
    public javax.swing.JCheckBox jCBAtivaSexta;
    public javax.swing.JCheckBox jCBAtivaTerca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JTable jTableDomingo;
    public javax.swing.JTable jTableQuarta;
    public javax.swing.JTable jTableQuinta;
    public javax.swing.JTable jTableSabado;
    public javax.swing.JTable jTableSegunda;
    public javax.swing.JTable jTableSexta;
    public javax.swing.JTable jTableTerca;
    public JFormattedTextField jTFDuracaoSegunda;
    public JFormattedTextField jTFDuracaoQuinta;
    private JLabel label;
    private JLabel label_1;
    public JFormattedTextField jTFDuracaoTerca;
    private JLabel label_2;
    public JFormattedTextField jTFDuracaoSexta;
    public JFormattedTextField jTFDuracaoQuarta;
    private JLabel label_3;
    public JFormattedTextField jTFDuracaoSabado;
    private JLabel label_4;
    public JFormattedTextField jTFDuracaoDomingo;
    private JLabel label_5;
}
